In [1]:
import pandas as pd
import networkx as nx
from xml.etree import ElementTree as ET
from tqdm import tqdm

In [2]:
df_cg = pd.read_csv('../edges/chemgene.csv',na_values=["N/A", "", "nan", "NaN", "NULL"],keep_default_na=False)
df_cd = pd.read_csv('../edges/chemdis.csv')
df_gd = pd.read_csv('../edges/genedis.csv',na_values=[ "N/A", "", "nan", "NaN", "NULL"], keep_default_na=False)

df_c = pd.read_csv('../vocab/CTD_chemicals.csv')
df_d = pd.read_csv('../vocab/CTD_diseases.csv')
df_g = pd.read_csv('../vocab/CTD_genes.csv',na_values=["N/A", "", "nan", "NaN", "NULL"],keep_default_na=False)

df_cg = df_cg[(df_cg['OrganismID'] == 9606)].drop_duplicates(subset=['ChemicalID', 'GeneSymbol'])
df_cd = df_cd.drop_duplicates(subset=['ChemicalID', 'DiseaseID'])  
df_gd = df_gd.drop_duplicates(subset=['GeneSymbol', 'DiseaseID'])

In [3]:
print(df_cg.info())
print(df_cd.info())
print(df_gd.info())

<class 'pandas.core.frame.DataFrame'>
Index: 812241 entries, 0 to 2993539
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ChemicalName        812241 non-null  object
 1   ChemicalID          812241 non-null  object
 2   CasRN               557625 non-null  object
 3   GeneSymbol          812241 non-null  object
 4   GeneID              812241 non-null  int64
 5   GeneForms           809771 non-null  object
 6   Organism            812241 non-null  object
 7   OrganismID          812241 non-null  float64
 8   Interaction         812241 non-null  object
 9   InteractionActions  812241 non-null  object
 10  PubMedIDs           812241 non-null  object
dtypes: float64(1), int64(1), object(9)
memory usage: 74.4+ MB
None
<class 'pandas.core.frame.DataFrame'>
Index: 3467034 entries, 0 to 9515672
Data columns (total 10 columns):
 #   Column               Dtype
---  ------               -----
 0   ChemicalName         object
 1   ChemicalID           object
 2   CasRN                object
 3   DiseaseName          object
 4   DiseaseID            object
 5   DirectEvidence       object
 6   InferenceGeneSymbol  object
 7   InferenceScore       float64
 8   OmimIDs              object
 9   PubMedIDs            object
dtypes: float64(1), object(9)
memory usage: 291.0+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34221 entries, 0 to 34220
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GeneSymbol      34221 non-null  object
 1   GeneID          34221 non-null  int64
 2   DiseaseName     34221 non-null  object
 3   DiseaseID       34221 non-null  object
 4   DirectEvidence  34221 non-null  object
 5   OmimIDs         5322 non-null   object
 6   PubMedIDs       29809 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.8+ MB
None

In [4]:
known = pd.read_csv('chemsmiles.csv')
known.head()

       meshID       cids                                             smiles
0     C070055      35823           C1=CC(=C(C=C1C2=CC(=C(C=C2Cl)Cl)Cl)Cl)Cl
1     C024713      12389                                     CCCCCCCCCCCCCC
2  D000077612     166548  CCCCCOC1=CC=C(C=C1)C2=CC=C(C=C2)C3=CC=C(C=C3)C...
3     C538809  131634859                  B(=O)OB1OB2OB(OB(O2)O1)[O-].[Na+]
4  C000626479       7565                      C1=CC=C(C=C1)OC2=CC=C(C=C2)Br

In [5]:
df_cg = df_cg[df_cg["ChemicalID"].isin(known["meshID"])]
df_cd = df_cd[df_cd["ChemicalID"].isin(known["meshID"])]
df_cd['DiseaseID'] = df_cd['DiseaseID'].str[5:]
df_gd['DiseaseID'] = df_gd['DiseaseID'].str[5:]
df_d['DiseaseID'] = df_d['DiseaseID'].str[5:]

print(df_cg.info())
print(df_cd.info())

<class 'pandas.core.frame.DataFrame'>
Index: 703832 entries, 0 to 2993539
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ChemicalName        703832 non-null  object
 1   ChemicalID          703832 non-null  object
 2   CasRN               551580 non-null  object
 3   GeneSymbol          703832 non-null  object
 4   GeneID              703832 non-null  int64
 5   GeneForms           701695 non-null  object
 6   Organism            703832 non-null  object
 7   OrganismID          703832 non-null  float64
 8   Interaction         703832 non-null  object
 9   InteractionActions  703832 non-null  object
 10  PubMedIDs           703832 non-null  object
dtypes: float64(1), int64(1), object(9)
memory usage: 64.4+ MB
None
<class 'pandas.core.frame.DataFrame'>
Index: 2911974 entries, 1 to 9515672
Data columns (total 10 columns):
 #   Column               Dtype
---  ------               -----
 0   ChemicalName         object
 1   ChemicalID           object
 2   CasRN                object
 3   DiseaseName          object
 4   DiseaseID            object
 5   DirectEvidence       object
 6   InferenceGeneSymbol  object
 7   InferenceScore       float64
 8   OmimIDs              object
 9   PubMedIDs            object
dtypes: float64(1), object(9)
memory usage: 244.4+ MB
None

In [6]:
chemicals = (set(df_cg['ChemicalID'].unique()) | set(df_cd['ChemicalID'].unique())) & set(known['meshID'])
genes = set(df_cg['GeneSymbol'].unique()) | set(df_gd['GeneSymbol'].unique())
diseases = set(df_cd['DiseaseID'].unique()) | set(df_gd['DiseaseID'].unique())

print(len(chemicals))
print(len(genes))
print(diseases)
print(len(chemicals)+len(genes)+len(diseases))

13943
28151

In [108]:
gene_emb = pd.read_csv('gtex_gene_tissue_expression.csv',na_values=["N/A", "", "nan", "NaN", "NULL"],keep_default_na=False)
gene_emb.head()

,EnsemblID,GeneSymbol,Whole Blood,Brain - Frontal Cortex (BA9),Brain - Cerebellar Hemisphere,Brain - Substantia nigra,Brain - Anterior cingulate cortex (BA24),Brain - Amygdala,Brain - Caudate (basal ganglia),Brain - Nucleus accumbens (basal ganglia),...,Liver - Hepatocyte,Pancreas - Mixed Cell,Pancreas - Islets,Pancreas - Acini,Liver - Portal Tract,Kidney - Medulla,Bladder,Cervix - Ectocervix,Cervix - Endocervix,Fallopian Tube
0,ENSG00000290825.2,DDX11L16,0.028955,0.018874,0.025773,0.017392,0.016015,0.018953,0.018269,0.021843,...,0.008585,0.002401,0.000000,0.005390,0.000000,0.009624,0.007607,0.009229,0.010787,0.013035
1,ENSG00000223972.6,DDX11L1,0.003192,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,ENSG00000310526.1,WASH7P,1.731737,0.944307,2.216555,0.795484,0.734542,0.681277,0.792692,0.787007,...,1.201638,1.357288,1.471623,1.541402,2.187545,1.714173,2.085198,2.291385,2.466782,2.514128
3,ENSG00000243485.6,MIR1302-2HG,0.011722,0.014546,0.023820,0.012514,0.010933,0.015694,0.012173,0.015497,...,0.026468,0.003592,0.000000,0.000000,0.000000,0.007528,0.021197,0.011385,0.026086,0.019993
4,ENSG00000237613.3,FAM138A,0.013435,0.026206,0.021936,0.024687,0.023050,0.021046,0.023017,0.027591,...,0.016027,0.000000,0.000000,0.005648,0.000000,0.010944,0.011410,0.018919,0.008539,0.023073

In [109]:
print(genes)
gene_emb = gene_emb[gene_emb["GeneSymbol"].isin(genes)]
gene_emb.info()

{'CIB2', 'LARP', 'C19ORF12', 'FAM21FP', 'SNX18P3', 'NXT2', 'GUSBP11', 'NRK', 'LIMD2', 'F13A1', 'ATXN7L1', 'C20ORF141', 'PCOLCE-AS1', 'PIGG', 'MIR3689D2', 'BRD1', 'CCDC9B', 'TTC31', 'SHC1', 'GH2', 'TAAR5', 'RIMS3', 'ESD', 'USP18', 'BICD1', 'TOPORS', 'OR5H2', 'VAMP1', 'FRMD5', 'BPIFA3', 'MTNAP1', 'ZNF414', 'FHL1P1', 'TCEAL1', 'NUDT16', 'ARAP1', 'SEC22C', 'CLEC3B', 'ZNF793', 'OSGEPL1-AS1', 'NXF5', 'RNU4-36P', 'PK', 'MESD', 'KRT18P30', 'WLS', 'TRAM1L1', 'ERVH-4', 'TMEM67', 'OR8D1', 'SNORA36C', 'PPHLN1', 'PSAPL1', 'RPLP1P4', 'MIR6739', 'PBP', 'TRABD2A', 'POLR3E', 'RPL10P7', 'ULBP2', 'ITGB3BP', 'GMIP', 'MS4A14', 'TRAC', 'KRTAP10-5', 'ALG1L6P', 'AFF1-AS1', 'UMPS', 'TUBB1', 'TPO', 'OTUD3', 'MYCBP', 'NKRF', 'CENPX', 'GRID2', 'STEAP3', 'FCAMR', 'FUOM', 'C12ORF71', 'CFAP144P1', 'YPEL4', 'SNORD111', 'IFT81', 'HIST1H2AL', 'SENP5', 'HACD3', 'WRNIP1', 'FAM224B', 'LITAF', 'E2F3', 'FALEC', 'NAP1L4', 'RAD51-AS1', 'DSC2', 'PRY2', 'PTTG3P', 'CIART', 'KRT222', 'TMEM246', 'CENPBD1P', 'MIR16-1', 'ZNF398', 'RNA28S5', 'CTNND1', 'LINC02147', 'CADM1', 'MIR643', 'JSRP1', 'ADCY7', 'PEX19', 'SPATA33', 'MIR4531', 'MIR193A-1', 'POLR2M', 'NLF2', 'KIAA1522', 'CEBPB-AS1', 'PEBP1', 'LINC01777', 'SMPD5', 'RPS20', 'MRPL4', 'RAB17', 'FAM83C', 'SMG1P1', 'SUGT1P3', 'FAM83H', 'PAFAH1B3', 'BCAT2', 'CYP2F2P', 'MEIS1-AS2', 'ELMO2', 'C4ORF50', 'MIR17', 'PRSS36', 'CENTD2', 'PDGFRA', 'PITPNM2', 'TBC1D7', 'BIN1', 'ZNF552', 'CHMP3', 'TSPAN17', 'CLCN3', 'ANKRD1', 'MUC3B', 'CHRNA5', 'ARMCX6', 'PRPF8', 'RPL7AP65', 'DNAJA2', 'RNU6-1045P', 'SETD9', 'CROCC2', 'ERGIC3', 'CCL14', 'HNRNPR', 'ZSCAN5C', 'PTBP3', 'SPATA9', 'SNORA7A', 'RNU6-367P', 'TVP23B', 'HRG', 'LINC00379', 'MIR6127', 'ZNF845', 'BDH2', 'SCOC-AS1', 'TMEM182', 'MIR6800', 'FTH1P20', 'CREG2', 'PIGR', 'MEF2C-AS1', 'NOS1', 'SNORD67', 'SOX6', 'MRPL14', 'HLF', 'LINC02449', 'KCTD13', 'AP5B1', 'LGI3', 'MIR4785', 'LRFN4', 'BMP15', 'FAM72A', 'CZ1P-ASNS', 'SETD4', 'RBM45', 'OIP5-AS1', 'UGP2', 'OR10J3', 'MAPKAPK5-AS1', 'USP27X-DT', 'GOLGA6L3P', 'UBQLNL', 'MIR4762', 'KRTAP19-7', 'FGF23', 'AP3S2', 'RABGAP1L', 'GPSM1', 'TLR3', 'RPL32P20', 'LNPK', 'MIR567', 'LSM8', 'FAM174B', 'LINC00836', 'GPR75-ASB3', 'ZFP110', 'PPP2R2A', 'HMGN1P30', 'ZNF470', 'ECEL1P1', 'RRAGA', 'RN7SL466P', 'NOP16', 'CYB561D1', 'AP4M1', 'SRGAP2', 'TMBIM1', 'PDZK1', 'ZNF430', 'HNRNPCP4', 'SP4', 'GPRIN3', 'GALNT3', 'NUFIP2', 'SH3RF2', 'MAP1A', 'C1ORF35', 'DDX18', 'TP53TG3F', 'DNAJB4', 'SCOC', 'HOXA1', 'EHD3', 'LINC01106', 'HNRNPA1P16', 'BPHL', 'AFAP1', 'SLC2A3P4', 'NCAPD2P1', 'UTS2B', 'DOC2GP', 'CGB5', 'SP7', 'ARMC7', 'SIGLECL1', 'LINC01231', 'TSEN2', 'C9ORF85', 'NLGN1', 'MPZL3', 'SH3GLB2', 'MED4-AS1', 'ULBP3', 'USP9X', 'BBX', 'BBS10', 'SFRS16', 'ARMS2', 'BARX1', 'NALF1', 'ARHGAP21', 'TSSK2', 'LURAP1L-AS1', 'UQCRFS1P1', 'CX3CL1', 'MIR6089', 'TBC1D10C', 'RGCC', 'CCDC13', 'PRR18', 'DUSP18', 'RNF216-IT1', 'TLR4', 'MIR210', 'C5', 'SNORA71E', 'ALYREF', 'CCNG2', 'TMEM65', 'DNAJB5-DT', 'LRRC55', 'FAM209B', 'LINC02139', 'ATP8B5P', 'MICU1', 'SNORA27', 'ODR-4', 'CFAP92', 'C1ORF52', 'DEPDC7', 'PAKAP', 'LUZP4', 'ZNF276', 'LILRB4A', 'CACNG1', 'KAZALD1', 'NIT2', 'STRA8', 'ZNF283', 'PWWP3B', 'ARFGEF1', 'ACVR1', 'ATP10A', 'MIR190B', 'POLH-AS1', 'NOTO', 'SPATA46', 'THAP1', 'GTF3C2', 'TBX1', 'LINC01366', 'DHRS2', 'RNF144B', 'KRT17P3', 'USP46', 'NRBP1', 'MIR34AHG', 'VPS33A', 'FAM214B', 'ZNF280D', 'SEMA5A', 'SMG8', 'MIR548H3', 'OTX2', 'NEUROD6', 'EAS', 'TMEM101', 'RPL23AP43', 'SERPINA1', 'BEAN1', 'SMIM15-AS1', 'MIR2278', 'TTC38', 'PGK1', 'ECE1', 'TMEM55A', 'DPEP2', 'HS3ST6', 'CDH10', 'PYGO1', 'ECHS1', 'STFA1', 'ADAM7', 'TMEM263-DT', 'CNTNAP3P2', 'RASSF7', 'TENM4', 'ABCC13', 'ELOVL1', 'TMED9', 'SPRR4', 'MDK', 'WFDC6', 'CHURC1', 'OSBPL7', 'NOXRED1', 'FOXO3B', 'MIR197', 'MIX23', 'LCMT1-AS2', 'ZMYM5', 'GPX-7', 'TAS1R2', 'DSTYK', 'SERBP1P5', 'SULT1C4', 'CCL3', 'GATD3B', 'SYCE2', 'H1F0', 'MIR548A1HG', 'LMO1', 'GPR75', 'HOPX', 'RARG', 'MIR656', 'OR3A1', 'ANG', 'TMED6', 'GTF2H1', 'SLC17A4', 'PAQR4', 'PACC1', 'CORO1A-AS1', 'ADAM5', 'KIAA1328', 'RHOX3H', 'SMIM10', 'ANXA6', 'CCL18', 'LINC01285', 'SLC39A12', 'SH2D7', 'SKP1P2', 'FBXL9P', 'RPL7AP37', 'SSTR2', 'HDAC8', 'SLC25A17', 'AQP3', 'OR2A20P', 'GCK', 'BCAS1', 'LAPTM4A', 'MIR450A2', 'TSTD1', 'MC5R', 'CLIC4P1', 'RPS3P6', 'NUSAP1', 'SNORD45A', 'SNCA', 'DDX18P1', 'KRTAP13-4', 'CCR8', 'WASH2P', 'UK114', 'RPAP3', 'LINC01914', 'TSC1', 'NUDT9P1', 'IFNA17', 'DCDC1', 'LINC01559', 'TREML5P', 'GAGE6', 'ATG12', 'NSUN5P1', 'SNHG14', 'ATP6V1G2', 'JUB', 'PLOD1', 'FKBP9P1', 'TUT4', 'CTAGE11P', 'CCDC51', 'EMX2', 'IGF2R', 'SHD', 'HBA2', 'KCNN4', 'RPS6KA5', 'LINC00269', 'SHISA8', 'VSTM1', 'GPR98', 'TTC23L', 'LRCH3', 'SANBR', 'ALOX12', 'JPH1', 'SREBF2', 'STS', 'POU3F4', 'MROH1', 'KDELR1', 'RLBP1', 'VWC2L', 'BRI3BP', 'MIR609', 'LINC02497', 'RP2', 'ZSWIM7', 'AP1B1', 'PKD1P5', 'FN3KRP', 'MIR1', 'GDAP1L1', 'GLP1R', 'ZNF212', 'TECPR1', 'MIR4288', 'MPG', 'NEMF', 'ETF1', 'GOLM2', 'GBA1LP', 'LINC01115', 'TTPAL', 'TEX36', 'LINC01526', 'ZNF473', 'ACTL9', 'SEMA6B', 'CCNT1', 'MSLN', 'RPS11', 'OR8I2', 'BARX2', 'TMEM225', 'IFIT1B', 'ALDH1A7', 'RNU6-490P', 'GOLPH3L', 'LINC01219', 'RPT-3', 'LINC02701', 'P2RY8', 'FBXO44', 'ANKRD34B', 'SIPA1L1', 'PTGDR', 'GUSBP5', 'KMT2D', 'FILNC1', 'HADHA', 'GFRA4', 'GPR32', 'BRF1', 'MTFP1', 'ANK', 'LINC00929', 'MSH2', 'ZNF254', 'MRPL1', 'FTLP10', 'HYAL1', 'MIR99A', 'GACAT1', 'CETN2', 'WNT10B', 'HOMER1', 'LAGE3P1', 'LRAT', 'MIR6875', 'SNORD139', 'C8ORF59', 'SNORA44', 'FABP5', 'TLK1', 'CFAP97', 'FASLG', 'CDRT15L2', 'SAMD3', 'USP17L22', 'TMEM35B', 'TILAM', 'RPL8', 'ZADH2', 'NUDT16-DT', 'ACBD3-AS1', 'HDHD3', 'TAGAP', 'LINC02535', 'SIGLEC8', 'CYP11A', 'RASA1', 'PTOV1-AS2', 'MIR8052', 'EFNB1', 'VN1R51P', 'DGAT2L7P', 'PPDPF', 'DRP2', 'GPR85', 'ACTR5', 'LMNB2', 'KCTD21', 'MTRNR2L3', 'H2BC5', 'FAM9A', 'HRASLS', 'LINC00605', 'PYGM', 'AAGAB', 'FAM114A2', 'LGI4', 'IFNG-AS1', 'AUTS2', 'CDH11', 'GNAT2', 'ZNF234', 'ZNF488', 'SAMM50', 'PTN', 'ZNF480', 'LACC1', 'TMEM209', 'SLC67A2', 'LAX1', 'RGL3', 'NEDD4L', 'BAG4', 'INSIG1-DT', 'P3H4', 'PPP1R17', 'LINC00475', 'HTR5A-AS1', 'CINP', 'PNOC', 'KLF6', 'MIR485', 'NBPF4', 'KLF3', 'TCIRG1', 'ETV3L', 'E2F1', 'IKBKE-AS1', 'MTCH2', 'SLC29A4P1', 'LINC01471', 'EAF2', 'WDR45B', 'DCAF8L2', 'TMEM233', 'ESRP1', 'TEX36-AS1', 'ALS2CL', 'FKSG29', 'RNF40', 'UBE2D3-AS1', 'ANGPTL3', 'LRRFIP2', 'VCAN-AS1', 'SNORA43', 'DCAF13', 'OR2A1-AS1', 'ANKRD20A8P', 'PGAM1P8', 'PCAT14', 'GEMIN2', 'CDC73', 'ZFP41', 'KRT19', 'MIMT1', 'SNORD36B', 'TIMM17A', 'TXNRD1', 'MAGEA9B', 'IL36RN', 'SMIM30', 'GARS', 'TSPAN15', 'RNA5-8SN2', 'PPP1R3C', 'OR7E106P', 'RNU6-1', 'GSTT2B', 'ACOX2', 'AMY1A', 'ATP6V1H', 'BMS1P1', 'MTARC1', 'ADGB', 'TRAF2', 'CALHM1', 'RNVU1-8', 'TENT4B', 'MEIS2', 'U2AF1L4', 'MBP', 'TEN1', 'SPANXA1', 'MIR545', 'ST8SIA3', 'CERS1', 'ARHGAP26-AS1', 'OR2T29', 'HAMP2', 'H2AC6', 'BTBD18', 'SESN1', 'CLDN17', 'POLK', 'PLEKHG4', 'TNF', 'SLC22A2', 'RNU6-1160P', 'ATP5ME', 'ZNF557', 'PTPRK', 'GCC2-AS1', 'FCGR3', 'LINC02405', 'GORAB', 'MBNL1-AS1', 'CEP55', 'MIR125B', 'LIX1L', 'RAMP2', 'RPS15AP1', 'HPN-AS1', 'COPZ2', 'P2RX6P', 'CPLX1', 'MIR4701', 'FANCE', 'ZNF528-AS1', 'MIR4302', 'SNORD84', 'MIR8083', 'TMEM205', 'H3C1', 'AP5M1', 'CCDC201', 'C4BPAP1', 'PTBP2', 'MIR133A-2', 'FAM136A', 'SHQ1', 'OR7E47P', 'HOXB6', 'F8A3', 'ADAM32', 'PTMAP10', 'LINC01098', 'SNAR-A3', 'SYCP1', 'OR4P4', 'ARL8A', 'SNORA25', 'ITGB3', 'CNEP1R1', 'UAP1', 'SNORD115-21', 'ARID4B', 'BPIFB2', 'KRT18P13', 'ZNF320', 'MDH2', 'ST18', 'PRXL2B', 'TRP73', 'SLC38A10', 'HCFC1-AS1', 'ZNF205', 'GBP3', 'KRT14', 'MIR124-3', 'MIR125A', 'KLF13', 'RNA5SP232', 'MIR500B', 'TFB2M', 'PDDC1', 'CERS5', 'ATP5MC1P5', 'MIR4644', 'TEDDM1', 'TCERG1L-AS1', 'PRMT5', 'DUSP23', 'TAS2R19', 'RPL21', 'SEPSECS-DT', 'TFAP2A', 'SLC38A5', 'TNIP2', 'IL27RA', 'NPHS1', 'IQUB', 'PLEKHA6', 'COMMD10', 'CATIP-AS1', 'OR9K2', 'OR7A19P', 'SINHCAFP2', 'RNY4P37', 'LYRM2', 'IFNA1', 'COL6A4P2', 'VDRB', 'CAPN2', 'VPS9D1-AS1', 'KIR2DL1', 'AGPAT4-IT1', 'TEAD1B', 'RORA-AS1', 'TLE3', 'SNORA26', 'PKD2L1', 'C5ORF51', 'TRAJ19', 'APOL6', 'LY6', 'ATL3', 'SERPINA1E', 'TBC1D9B', 'MFSD11', 'LRRC37A', 'FANCL', 'GNAL', 'DMRTC1', 'ZNF658B', 'EIF1AXP1', 'BANF2', 'KRT8P31', 'TNFSF4', 'LINC02568', 'RBM46', 'B3GALT9', 'RIBC2', 'GNA12', 'APCS', 'PATZ1', 'NDRG3', 'IGLC2', 'DNAJC10', 'SYNPO', 'BEX3', 'PRICKLE2', 'CCDC83', 'ERAP2', 'HIST2H3C', 'SCN2B', 'UNC5CL', 'SPRY4-IT1', 'MIR614', 'SLC9A3R1', 'RAD17', 'TADA1', 'ANKRD16', 'KIAA0319', 'LINC01169', 'RPL17P33', 'RPL19P9', 'DNAJC5', 'PCDH11Y', 'PRDM10', 'PMM2', 'HSPB2', 'EB1', 'PRKRA', 'ROPN1', 'ARL10', 'GLOD4', 'ARHGAP5-AS1', 'FIBP', 'GPC1', 'ACTL6B', 'CC2D1B', 'HIST1H3B', 'PSMA6', 'F2RL2', 'KRTAP4-11', 'OXCT2P1', 'KCNJ15', 'VCY1B', 'MIR3165', 'DCXR-DT', 'SLC2A2', 'LINC01121', 'COL5A1-AS1', 'SRRD', 'GUCY2G', 'C19ORF33', 'IGKC', 'HBG1', 'RRM2', 'GRAPL', 'FANK1', 'LINC01776', 'FKBP14', 'USP32P3', 'TMEM230', 'CPEB1-AS1', 'RIIAD1', 'ERP27', 'THOC2', 'TUBB5', 'CFAP144', 'PARP8', 'CAPNS1', 'NBEAP1', 'COX10-DT', 'HBBP1', 'RAD9B', 'RNASE7', 'RPSAP47', 'PCDHA3', 'TBC1D15', 'RIMKLA', 'PYCARD-AS1', 'PEMT', 'SNORD91A', 'SLC13A2', 'MTSS1', 'TCERG1', 'SPIN3', 'OR2L1P', 'SDAD1P1', 'LINC00674', 'MIR4740', 'XAGE1A', 'ANKRD10', 'MIR592', 'DDX23', 'FREM2', 'MIR520H', 'MIR4315-1', 'ESRRB', 'FOXO1A', 'UPF3AP3', 'ATP13A4-AS1', 'ATOH1', 'URI1', 'ZNF559-ZNF177', 'HLTF', 'LINC01013', 'CALN1', 'LINC01409', 'RPL14P1', 'SLC7A7', 'OR1L3', 'PCDHA11', 'ALG2', 'TTLL7', 'ZFP62', 'MIR687', 'MIR4664', 'RPL10P8', 'KRTAP22-1', 'A1BG', 'RNF138', 'ATP10B', 'TSPAN3', 'PHKA1', 'MIR4442', 'CSE1L', 'OSR2', 'HMGN3-AS1', 'LINC01493', 'LPO', 'RPL21P16', 'SULT1B1', 'MTBL', 'BLTP3A', 'PTGS2A', 'ZNF706', 'LINC01020', 'OR7E14P', 'SPPL2A', 'CTSC', 'ZBTB22', 'ACKR2', 'PLA2G3', 'UTS2', 'SLCO1A2', 'MUC12', 'DDB1', 'HMBOX1', 'TCF25', 'MIR4268', 'SETP14', 'SRBD1', 'SHLD3', 'MIR4477A', 'RAET1E', 'SMIM14-DT', 'FNDC8', 'DAPK1', 'ZFAT', 'INVS', 'SCRT1', 'GOLGA8N', 'CNTNAP3B', 'GC', 'UVRAG-DT', 'ZBTB2', 'CSTF2T', 'TFDP2', 'SNX15', 'ADH6', 'RHOXF1P1', 'PDE11A', 'ATP8A2', 'RHO', 'SLC35D4', 'RPL7AP45', 'IRF9', 'PTPN3', 'SEC1', 'TUBBP10', 'KDM5D', 'FAM13B', 'MARK2P9', 'ASAH2', 'MPI', 'ILDR1', 'GOLIM4', 'H1-10', 'MIR10398', 'PODNL1', 'GRASLND', 'DNAI2', 'H2BC9', 'SAMD15', 'EEF1A1P12', 'Y62H9A.3', 'LMTK3', 'WDR5', 'MORN5', 'TRMT9B', 'GRIK3', 'CLTA', 'ASPA', 'ARID3C', 'USP17L18', 'ZBTB33', 'ZFP207', 'OR13C3', 'POP1', 'CA15P1', 'BSP', 'SLC1A4', 'RPS27P1', 'SRMS', 'LINC01118', 'MATN1-AS1', 'SLC24A2', 'FLVCR2-AS1', 'MIRLET7BHG', 'FRAT1', 'MFAP3L', 'GEMIN6', 'IGLV1-50', 'ERI2', 'KIR2DL3', 'ADAMTS7', 'CSTPP1', 'LRRC14B', 'MIR155', 'JAK2', 'LNX1', 'IGKV3D-15', 'LINC01484', 'CD34', 'STRTS', 'PHKG1P2', 'LRIG2-DT', 'CYP24A1', 'PLA2G10', 'PGM3', 'H1-6', 'AHCYP7', 'MIR941-3', 'C14ORF2', 'LRRC18', 'IGHV3', 'SPDYE9', 'FGF3', 'CD300LG', 'SLC28A3', 'NLRP10', 'CWC22', 'SLC35B3', 'ZDHHC1', 'NRIP3', 'MIR100', 'BMP7-AS1', 'RHBG', 'ZFP106', 'ADGRG5', 'SERPINB2', 'LINC01142', 'ZDHHC24', 'ROPN1B', 'ZC3H10', 'MON1A', 'ACNATP', 'SVIL-AS1', 'ADGRA2', 'FKBP8', 'MIR631', 'KLHL31', 'TH1L', 'SPATA3', 'TRA2A', 'MXD4', 'SLC18A2', 'ETS2', 'RNA5SP221', 'GKN2', 'ELOA-AS1', 'ARHGAP19-SLIT1', 'C2', 'WDR34', 'CCL26', 'CCDC140', 'RN7SL470P', 'RBMY1J', 'HNF4A', 'USP34-DT', 'TREX1', 'SPDEF', 'TBX3', 'DNMT3B', 'CHD5', 'IQSEC2', 'LINC02092', 'CCDC63', 'RCC2P7', 'CTSLP8', 'SUMO1P3', 'MIR1302-5', 'ABHD2', 'MACROD2', 'TSSK4', 'PSMB9', 'HMGB1P41', 'SBF1P1', 'VCPKMT', 'MIR4458HG', 'LNCBRM', 'GS1-279B7.1', 'PGS1', 'MIR583', 'TTC3-AS1', 'JADE1', 'LINC01202', 'LCE3D', 'BCRP7', 'NEXN-AS1', 'COG5', 'PSME3IP1', 'RPL7P32', 'NK4', 'LINC01798', 'STEAP2', 'RPL23AP32', 'PKNOX1', 'ZSCAN1', 'MIR518B', 'BNIP3P2', 'KATNIP', 'TIGIT', 'MUC17', 'SLC26A7', 'MPRIP', 'DTNBP1', 'LINC00710', 'GPR27', 'PARN', 'H3-7', 'VTI1BP2', 'SNORD116-14', 'MSMB', 'FAF2', 'ZNF56P', 'DMXL2', 'SECTM1B', 'IL4I1', 'NEU2', 'HSPA6', 'LINC02000', 'ANKRD20A1', 'BEST4', 'MLANA', 'ZNF592', 'COX6B1P1', 'TSLP', 'PARP4', 'L1TD1', 'SRRM5', 'BMAL1', 'SLC27A3', 'SAMD12', 'MCAT', 'TOMM70A', 'COX6B2', 'LINC01270', 'ANKRD20A9P', 'ZNF14', 'SPATA19', 'ABCA2', 'ASNSP3', 'SNORD26', 'TRDN', 'GABBR2', 'SERPINE2', 'ZNF8', 'GRIN1A', 'SATB1', 'SHROOM3', 'LINC02133', 'CPA5', 'CIRBP-AS1', 'APOL5', 'CLK2', 'MAGEA5P', 'ATRAID', 'TP53TG3C', 'PTENP1', 'NAA10', 'FAM134B', 'CHRNA2', 'RPL26L1-AS1', 'TMEM184C', 'TADA3', 'CUL4A', 'UCKL1', 'TAF3', 'BPTFP1', 'PLA2G4E', 'STXBP4', 'LCE2C', 'ZCCHC13', 'KRABD3', 'SRP68', 'SMOX', 'GPX8', 'PSG9', 'ZDHHC9', 'FAM241B', 'PRR20B', 'ANKRD62', 'PRRC1', 'USP17L12', 'MIR4476', 'ENTPD1-AS1', 'HIGD1C', 'CDCA8', 'IZUMO4', 'H4C11', 'GTF2IP12', 'ARHGAP26', 'OR2M4', 'CYP26B1', 'NUDT11', 'H1FX', 'MYBBP1A', 'CTNS-AS1', 'CAPN9', 'CBX6', 'EGLN2', 'LINC01932', 'DNAJC6', 'SETD7', 'GID8', 'VPS4A', 'PCAT4', 'NRSN1', 'CDC20-DT', 'RPL7AP26', 'BCL2L1', 'DACT3', 'EIF2B3', 'ZNF586', 'RASGRF2', 'DRC8', 'GLRB', 'WDR6', 'SETMAR', 'MUC20P1', 'AAMP', 'USF2', 'ITGA2B', 'ZC3H12B', 'GNAO1', 'RHEBP2', 'FFAR2', 'C11ORF86', 'CNTNAP5C', 'FAM151B', 'HAS1', 'SKP2', 'PCNX2', 'SIL1', 'MEMO1', 'TDRD9', 'PCAT18', 'KMT2C', 'LBX1', 'CD7', 'MTRNR2L4', 'PPIEL', 'CCDC54', 'AFAP1L2', 'VSTM5', 'KLHL23', 'B3GALT4', 'RNF175', 'C5ORF46', 'NDUFA5', 'LINC00882', 'CYP2C19', 'STX4A', 'CLEC12B', 'PM20D2', 'MIR4800', 'PSMG3-AS1', 'PGCP', 'ELMO1', 'ITGA3', 'GLS', 'PTGER4', 'ADK', 'NTN1', 'CNTNAP5A', 'PIH1D1', 'BMS1P20', 'TMOD1', 'RPL32P29', 'ACOD1', 'TAS2R1', 'MIR936', 'NKIRAS2', 'TSPAN10', 'BDKRB1', 'TRIP4', 'MCM5', 'POLE', 'RTP5', 'TFIP11', 'Y110A2AL.9', 'RNASEH2B-AS1', 'ANXA2P1', 'CDC42EP1', 'PRSS22', 'TUSC7', 'PCNXL4', 'SLC35D1', 'DYNLL1', 'OTX2OS1', 'MPIG6B', 'DUS3L', 'THNSL1', 'MMP24', 'LINC01928', 'LRMP', 'HRNR', 'SLTM', 'ISCU', 'MAN2C1', 'TMEM181', 'HSD17B11', 'LRRC28', 'SLC8A2', 'TTC23', 'FAM120A2P', 'CASTOR1', 'SPIB', 'SOD3', 'SNORA10', 'KIAA1656', 'CCN5', 'HIF1AN', 'RIMOC1', 'HRH1', 'PRRC2B', 'ENO3', 'CIR', 'MIR99AHG', 'RAMAC', 'H2AJ', 'TCEAL3', 'CLMP', 'MIR193B', 'XKR9', 'PCDHB8', 'MYOZ3', 'OR10W1', 'RNY3P5', 'FARP1', 'LAMA5-AS1', 'IL21R-AS1', 'ZNF238', 'LINC01391', 'ALG13', 'CCDC82', 'ZSCAN16-AS1', 'TTTY1B', 'RFX6', 'ZNF786', 'DAPK1-IT1', 'CLIC1', 'CREBRF', 'ZFP42', 'CYCB', 'KBTBD6', 'MYOM3', 'NIFK', 'DDR1', 'LRR1', 'RPL12', 'IGG1C', 'FHL1', 'CSF1', 'MAP4K3', 'LINC02902', 'GIPC2', 'PYY2', 'SLC35D3', 'FCN1', 'MIR663A', 'TSBP1', 'C12ORF60', 'PDE6A', 'SNORD44', 'XAF1', 'HERC5', 'SMYD1', 'RFPL4AL1', 'MLH3', 'CNIH3-AS2', 'PPIB', 'UCK1', 'REXO1', 'SRSF1', 'CARS2', 'ZNNT1', 'RPL4P6', 'GAPDHP71', 'DEGS2', 'HIST1H4A', 'OLR1', 'NIPA1', 'KLRC4', 'CRPPA', 'MIR4255', 'ABCE1', 'HMOX1', 'TAPT1-AS1', 'CD109', 'SNRNP70', 'TRIB3', 'FZD4-DT', 'DNAJC21', 'SFR1', 'TARS3', 'TUBAP2', 'HMGN1P8', 'EFCAB7', 'DRG2', 'RTCB', 'CIMIP2B', 'MLLT11', 'ADAM23', 'NPIPB11', 'PCID2', 'EMB', 'SPDL1', 'ERBB2', 'NEMP1', 'MIR938', 'MIR20B', 'GOLGA2', 'OR2T8', 'OR10AD1', 'RBMS1P1', 'WHT-6', 'DUOXA1', 'LINC01949', 'ZNF524', 'MIR7150', 'CELSR2', 'BIK', 'DNAJC22', 'RPS4XP14', 'UGT1A2P', 'RCC1', 'FGFBP1', 'SKINT1L', 'ABRAXAS2', 'ERVV-2', 'SLC16A4', 'CROP', 'SECTM1', 'BMS1P2', 'RHOXF1P3', 'HEY2', 'MAPK8IP1P2', 'RFXAP', 'FAM74A3', 'FARP2', 'STMN2', 'COL20A1', 'NRX-1', 'FTLP2', 'CUTALP', 'USP17L19', 'HP1BP3', 'PWWP3A', 'LINC02567', 'ADIRF', 'RPS2P20', 'MUC15', 'TMEM62', 'P2RX5', 'CREB3L2', 'DNAJB2', 'IL13RA2', 'RNF11', 'MRLN', 'ZNF324', 'PPP4R1L', 'MAP3K12', 'PAPPA', 'BHLHE23', 'ACADSB', 'OPA3', 'GGTA2P', 'C19ORF38', 'AHDC1', 'DUSP8', 'WDR77', 'UBE2J1', 'GNPNAT1', 'PCAT6', 'MIR937', 'CDHR5', 'LINC01227', 'CENPU', 'FARSB', 'LINC01885', 'HTR3A', 'RN7SL32P', 'ITGB6', 'ZNF541', 'CDH12P3', 'GOT1-DT', 'TYRP1', 'CPA2', 'FMC1', 'KAT8', 'RNA5SP481', 'PTPRH', 'LRRC51', 'ZNF140', 'TMX3', 'LYPD4', 'FRG1JP', 'RADX', 'OR5V1', 'ALG1L9P', 'DOCK9', 'ADAM21P1', 'COL18A1', 'THBS4', 'PTCSC2', 'PEA15A', 'CMTR2', 'TCFL5', 'COMMD8', 'DPY19L1P2', 'H4C6', 'ITPA', 'F2', 'LINC00417', 'EIF3J-DT', 'DUSP26', 'KDSR', 'LINC02404', 'IPO11', 'TMEM69', 'SPATA12', 'LINC01567', 'UBE2SP1', 'SLC38A4', 'METTL2A', 'CXADR', 'KIR2DL4', 'H2AX', 'RBM4B', 'SLC25A12', 'PDE7B-AS1', 'PSMA7', 'CCDC135', 'HSF4', 'TDRD10', 'PYDC1', 'ACVR1C', 'MON2', 'ZNF580', 'KRT6B', 'KLRC3', 'DGAT1', 'LOH12CR2', 'GATAD2A', 'EGFL8', 'GDPD5', 'POLR2J4', 'LINC02331', 'MIR505', 'LINC00370', 'DLGAP1-AS1', 'SNORD5', 'CEP97', 'PNMA1', 'MIR1302-2', 'CCDC122', 'TSPAN1', 'OR52E5', 'PRR20D', 'CIR1', 'ESCO2', 'MIR548N', 'COLGALT1', 'SPINT3', 'ADAM22', 'MAP3K11', 'H3C3', 'GABRB3', 'DDX4', 'CICP16', 'MIR130B', 'LINC02846', 'HPR', 'LINC01975', 'ZNF236', 'ALKBH3', 'ACKR3', 'SSTR4', 'MT1A', 'NPY6R', 'MBTD1', 'ACVR2A', 'CLCN1', 'TGM4', 'LRIT2', 'SNORA13', 'MKRN1', 'ABCG4', 'MIR374B', 'RNU4-2', 'ZFP14', 'MIR6809', 'SEMA4F', 'DEXI', 'RPA2', 'IHO1', 'PJA2', 'SNCAIP', 'RPL37P6', 'DIRC3-AS1', 'RHOXF2B', 'MRFAP1L2', 'CDK1', 'AGR2', 'KRT7', 'ZNF696', 'IPO13', 'BICD2', 'F46G10.1', 'SDCCAG8', 'ZSCAN25', 'UBE2C', 'SH3RF1', 'MIR5580', 'GJB7', 'SNORA29', 'IGKV1-5', 'EFCAB3', 'MCCC1-AS1', 'SLC34A1', 'SGCD', 'CCDC42', 'RAB34', 'CYP1A2', 'XPO4', 'PTPN12', 'PRR23B', 'EME2', 'ICAM3', 'XAGE3', 'ICAM4', 'MIR3179-2', 'TIMM50', 'EIF3EP1', 'ARPC5L', 'ENPP2', 'KNG1', 'RPS4XP2', 'AS3MT', 'SLC39A3', 'TACC1', 'ELAC2', 'PCDHAC2', 'CMAH', 'CD93', 'TMEM269', 'TIGD5', 'TXNIP', 'VTI1B', 'BAZ2B', 'SDR39U1', 'RMND5A', 'HSD11B1', 'PRKY', 'PSME1', 'HSD17B1', 'SAMSN1', 'SLAMF6', 'NTRAS', 'SNAI3-AS1', 'MIR548AK', 'GSTP2', 'IGLV1-44', 'FEM1A', 'CDK17', 'SMAD4', 'TAAR3', 'CMA1', 'ALDH1A3', 'OGFOD3', 'NAA16', 'RPL37AP8', 'ZNF518A', 'DHFRP1', 'SNL', 'SKI', 'CRIP3', 'KIF3A', 'MIR4739', 'ZKSCAN2', 'OSBP', 'ALG9', 'LINC02385', 'MYL6B', 'OXA1L-DT', 'MTSS2', 'ZNF180', 'PANTR1', 'RHBDL2', 'OR5M9', 'PCBP4', 'TAF2', 'TAS2R20', 'ZFAND3', 'HEBP2', 'ABCF3', 'DYRK3', 'F9', 'TLNRD1', 'CCDC71', 'PPIAL4F', 'CCDC159', 'TTC21B-AS1', 'BUB1B', 'PSMD12', 'TERB1', 'N4BP2L1', 'TNP1', 'ATP8B1', 'RPL35AP26', 'KLHL6', 'ALOX15', 'NISCH', 'KRABD5', 'PPP4R2', 'IGLV5-45', 'BEX1', 'ESCO1', 'ATP5PD', 'RNU6-529P', 'GAB4', 'KLLN', 'TIPIN', 'RNA5SP303', 'TGFB1A', 'EMP3', 'GAN', 'ZNF22', 'ANGPTL4', 'INS1', 'CCS', 'UCHL5', 'GALNT12', 'KHNYN', 'PTCHD3P3', 'CMTM4', 'MAPK8IP3', 'CCDC124', 'MMS22L', 'QKI', 'KLHL1', 'JAKMIP2-AS1', 'SH3BP2', 'NALCN', 'PRDM14', 'IRF5', 'RPS12P27', 'C19ORF18', 'REPS1', 'PAX1', 'KANK1', 'ZC3H12C', 'RSPO4', 'TNFRSF10A-AS1', 'CTBP1', 'ZNF555', 'GTPBP10', 'RN7SKP269', 'WFDC12', 'SNORD20', 'HMGCS1', 'ZNF512B', 'MYO19', 'PRR9', 'SATB1-AS1', 'MIR520F', 'CPNE3', 'B3GALNT1P1', 'MRPL45P2', 'LINC02482', 'EEF1A1P22', 'L3MBTL4', 'LINC02897', 'GRIK1', 'TTF2', 'SCAF8', 'RAB33A', 'MIR29B', 'PCDHB16', 'FAM21EP', 'SCARA5', 'LRP4-AS1', 'ASPN', 'STOM', 'PPM1L', 'CCDC90B', 'MERTK', 'ADAMDEC1', 'TNRC6A', 'USP24', 'OR51V1', 'NPM1P22', 'NFKBIE', 'OR51L1', 'MIR30B', 'DCPH1', 'GGT2P', 'RPL7AP62', 'NAPSB', 'ATP2B2', 'POLR3K', 'PPP1R14C', 'ATXN7L2', 'SIAE', 'MAMDC2', 'RTTN', 'NKX6-3', 'ANKHD1', 'PLEC', 'PACSIN1', 'PPM1J', 'RIN1', 'DPEP3', 'RANP4', 'LPL', 'PRY', 'CDK2AP2', 'USP47', 'PTTG2', 'MIR122', 'KLHL28', 'KRTAP4-2', 'RFESD', 'ADAMTS1', 'MIR635', 'NCSTN', 'MIR349', 'LRRC63', 'KIAA1755', 'SNRPGP10', 'STARD10', 'BLMH', 'FAM230B', 'PGP', 'KLKP1', 'TUBB2B', 'TRAPPC4', 'ADH5P2', 'OR52A4P', 'FAAP100', 'VAX2', 'MANF', 'MDGA1', 'TCAF2P1', 'LGALS7', 'ZNF132', 'TM4SF18', 'PRELID2', 'MIR6879', 'INTS6L', 'OGFOD1', 'ALPK2', 'AREL1', 'KRTAP12-1', 'EFTUD2', 'CTBS', 'CYB5B', 'RBFOX1', 'IL21R', 'IL36G', 'SPAG7', 'GCNT3', 'PURPL', 'LINC00852', 'KRT84', 'C6ORF62', 'ABCB5', 'HNRNPH1', 'SPRY2', 'B4GALT5', 'POM121', 'UGT2B34', 'H2BW2', 'ZNF618', 'ZNF141', 'ARGLU1', 'CARD19', 'IGLV7-46', 'LINC01362', 'TMEM25', 'GCAWKR', 'PRRT3', 'IGKV1OR2-118', 'CYP2B2', 'HEMK2', 'PPP2R3C', 'CHRNA7', 'ME3', 'GABRE', 'CXCR3', 'HNRNPCL2', 'GIGYF2', 'ADIPOQ', 'JPT1', 'NOD2', 'MAN2A1', 'MIDN', 'LINC02162', 'NDUFS1', 'STRA6', 'HSPA8', 'RPL27AP', 'RAD18', 'VIRMA', 'LINC01556', 'NDUFAF5', 'BHLHE40-AS1', 'SLC35D2', 'AKR1C7P', 'ADH5P4', 'CCDC61', 'FABP5L2', 'RPS3AP6', 'UHRF1', 'CTSK', 'LINC01354', 'ZNF350', 'RNF225', 'FXN', 'UTP6', 'RBM42', 'FANCM', 'PTP4A3', 'SAXO2', 'SNORA70', 'CHEK2', 'KRT80', 'PPP1R3B', 'ZNF219', 'LINC03040', 'LINC01148', 'FTH1P2', 'SDR16C6', 'SERPINI2', 'ERVK3-2', 'MIR6815', 'NOP56P2', 'THRA', 'MROH7', 'UPK1B', 'KRTAP1-1', 'DSEL', 'H19', 'KCND3', 'RPS15AP12', 'SNORA35', 'SPRR2C', 'POLR3H', 'MIR642B', 'PRB4', 'THUMPD2', 'BLTP2', 'PARD6G-AS1', 'AGBL1', 'CLPTM1', 'SNORD114-2', 'NAA15', 'PPP2R1B', 'RANBP2', 'LYSMD3', 'ARHGEF5', 'J

In [110]:
x = gene_emb.loc[gene_emb['GeneSymbol'] == 'CIB2'].values.flatten().tolist()[2:]
print(len(x))

68

In [7]:
G = nx.Graph()

for chem in chemicals:
    G.add_node(chem, node_type='chemical')
for gene in genes:
    G.add_node(gene, node_type='gene')
for disease in diseases:
    G.add_node(disease, node_type='disease')

for _, row in df_cg.iterrows():
    G.add_edge(row['ChemicalID'], row['GeneSymbol'], edge_type='chem_gene')
for _, row in df_cd.iterrows():
    G.add_edge(row['ChemicalID'], row['DiseaseID'], edge_type='chem_disease')
for _, row in df_gd.iterrows():
    G.add_edge(row['GeneSymbol'], row['DiseaseID'], edge_type='gene_disease')

In [8]:
import numpy as np

np.set_printoptions(linewidth=10**9)

with open("edges.txt", "w") as f:
    for g in G.edges(data=True):
        f.write(str(g) + "\n")

In [113]:

print(f"Graph built: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges")
print(G.nodes(data=True))

Graph built: 49333 nodes, 3650027 edges

In [114]:
# df_c = df_c[['ChemicalID', 'ChemicalName', 'PubChemCID']].drop_duplicates(subset=['ChemicalID']).set_index('ChemicalID')
# df_d = df_d[['DiseaseID', 'DiseaseName', 'DiseaseSemanticType']].drop_duplicates(subset=['DiseaseID']).set_index('DiseaseID')
# df_g = df_g[['GeneSymbol', 'GeneSymbol', 'GeneName']].drop_duplicates(subset=['GeneSymbol']).set_index('GeneSymbol')


print(df_c.info())
print(df_g.info())
print(df_d.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179408 entries, 0 to 179407
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ChemicalName       179408 non-null  object
 1   ChemicalID         179408 non-null  object
 2   CasRN              56623 non-null   object
 3   Definition         6190 non-null    object
 4   ParentIDs          179407 non-null  object
 5   TreeNumbers        179408 non-null  object
 6   ParentTreeNumbers  179407 non-null  object
 7   Synonyms           116886 non-null  object
dtypes: object(8)
memory usage: 11.0+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 641489 entries, 0 to 641488
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   GeneSymbol   641489 non-null  object
 1   GeneName     639154 non-null  object
 2   GeneID       641489 non-null  int64
 3   AltGeneIDs   48428 non-null   object
 4   Synonyms     267672 non-null  object
 5   BioGRIDIDs   36297 non-null   object
 6   PharmGKBIDs  24838 non-null   object
 7   UniProtIDs   289215 non-null  object
dtypes: int64(1), object(7)
memory usage: 39.2+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13317 entries, 0 to 13316
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   DiseaseName        13317 non-null  object
 1   DiseaseID          13317 non-null  object
 2   AltDiseaseIDs      5593 non-null   object
 3   Definition         5181 non-null   object
 4   ParentIDs          13316 non-null  object
 5   TreeNumbers        13317 non-null  object
 6   ParentTreeNumbers  13316 non-null  object
 7   Synonyms           11317 non-null  object
 8   SlimMappings       13301 non-null  object
dtypes: object(9)
memory usage: 936.5+ KB
None

In [115]:
df_g = df_g[df_g["GeneSymbol"].isin(genes)]
df_g.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28150 entries, 15907 to 641485
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GeneSymbol   28150 non-null  object
 1   GeneName     28097 non-null  object
 2   GeneID       28150 non-null  int64
 3   AltGeneIDs   20826 non-null  object
 4   Synonyms     26174 non-null  object
 5   BioGRIDIDs   20212 non-null  object
 6   PharmGKBIDs  21696 non-null  object
 7   UniProtIDs   20417 non-null  object
dtypes: int64(1), object(7)
memory usage: 1.9+ MB

In [116]:
paths = pd.read_csv('CTD_pathways.csv')
paths.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2567 entries, 0 to 2566
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PathwayName  2567 non-null   object
 1   PathwayID    2567 non-null   object
dtypes: object(2)
memory usage: 40.2+ KB

In [117]:
dpath = pd.read_csv('../vocab/dispath.csv')
cpath = pd.read_csv('../vocab/chempath.csv')
gpath = pd.read_csv('../vocab/genepath.csv')

dpath['DiseaseID'] = dpath['DiseaseID'].str[5:]

cpath = cpath.drop_duplicates(subset=['ChemicalID', 'PathwayID'])  
gpath = gpath.drop_duplicates(subset=['GeneSymbol', 'PathwayID'])
dpath = dpath.drop_duplicates(subset=['DiseaseID', 'PathwayID'])

print(dpath.head())
print(diseases)

cpath = cpath[cpath["ChemicalID"].isin(chemicals)]
gpath = gpath[gpath["GeneSymbol"].isin(genes)]
dpath = dpath[dpath["DiseaseID"].isin(diseases)]

print(dpath.info())
print(cpath.info())
print(gpath.info())

                                  DiseaseName DiseaseID  \
0  17-Hydroxysteroid Dehydrogenase Deficiency   C537805
1  17-Hydroxysteroid Dehydrogenase Deficiency   C537805
2  17-Hydroxysteroid Dehydrogenase Deficiency   C537805
3  17-Hydroxysteroid Dehydrogenase Deficiency   C537805
4  17-Hydroxysteroid Dehydrogenase Deficiency   C537805

                                         PathwayName            PathwayID  \
0                              Androgen biosynthesis   REACT:R-HSA-193048
1  Fatty acid, triacylglycerol, and ketone body m...   REACT:R-HSA-535734
2                        Fatty Acyl-CoA Biosynthesis    REACT:R-HSA-75105
3                                 Metabolic pathways        KEGG:hsa01100
4                                         Metabolism  REACT:R-HSA-1430728

  InferenceGeneSymbol
0             HSD17B3
1             HSD17B3
2             HSD17B3
3             HSD17B3
4             HSD17B3

In [118]:
pathways = set(dpath['PathwayID'].unique()) | set(cpath['PathwayID'].unique())  | set(gpath['PathwayID'].unique())
len(pathways)

2363

In [119]:
# Group PathwayIDs by DiseaseID
dpaths = dpath.groupby("DiseaseID")["PathwayID"].apply(list).reset_index()
dpaths = dpaths.rename(columns={"PathwayID": "PathwayIDs"})
dpaths.set_index('DiseaseID',inplace=True)
print(dpaths)
# Convert to list of dictionaries
result_dp = dpaths.to_dict(orient="records")

                                                  PathwayIDs
DiseaseID
102200     [REACT:R-HSA-8937144, REACT:R-HSA-211859, REAC...
105500     [REACT:R-HSA-983712, KEGG:hsa04978, KEGG:hsa04...
106190     [REACT:R-HSA-1280218, KEGG:hsa04925, KEGG:hsa0...
108120     [KEGG:hsa04261, KEGG:hsa04260, KEGG:hsa05414, ...
108420     [REACT:R-HSA-1640170, REACT:R-HSA-1500620, REA...
...                                                      ...
D066087    [REACT:R-HSA-1296052, REACT:R-HSA-418457, KEGG...
D066088    [REACT:R-HSA-74160, REACT:R-HSA-983712, REACT:...
D066126    [REACT:R-HSA-166054, REACT:R-HSA-5617472, REAC...
D066253    [KEGG:hsa05412, REACT:R-HSA-380108, KEGG:hsa04...
D066263    [KEGG:hsa05014, REACT:R-HSA-2262752, REACT:R-H...

[5051 rows x 1 columns]

In [120]:
# Group PathwayIDs by DiseaseID
gpaths = gpath.groupby("GeneSymbol")["PathwayID"].apply(list).reset_index()
gpaths = gpaths.rename(columns={"PathwayID": "PathwayIDs"})
gpaths.set_index('GeneSymbol',inplace=True)

# Convert to list of dictionaries
result_gp = gpaths.to_dict(orient="records")

print(len(result_gp))

11458

In [121]:
# Group PathwayIDs by DiseaseID
cpaths = cpath.groupby("ChemicalID")["PathwayID"].apply(list).reset_index()
cpaths = cpaths.rename(columns={"PathwayID": "PathwayIDs"})
cpaths.set_index('ChemicalID',inplace=True)
print(cpaths)
# Convert to list of dictionaries
result_cp = cpaths.to_dict(orient="records")

print(len(result_cp))

                                                   PathwayIDs
ChemicalID
C000015     [REACT:R-HSA-382556, KEGG:hsa02010, KEGG:hsa04...
C000050     [REACT:R-HSA-1368108, REACT:R-HSA-156590, REAC...
C000081     [REACT:R-HSA-442660, REACT:R-HSA-112316, REACT...
C000121     [REACT:R-HSA-166054, REACT:R-HSA-450341, KEGG:...
C000154     [REACT:R-HSA-111447, REACT:R-HSA-111459, REACT...
...                                                       ...
D064753                  [KEGG:hsa05418, REACT:R-HSA-6785807]
D064791     [REACT:R-HSA-166054, KEGG:hsa04920, KEGG:hsa05...
D065146     [REACT:R-HSA-450341, KEGG:hsa05221, KEGG:hsa04...
D065366     [REACT:R-HSA-166054, REACT:R-HSA-450341, KEGG:...
D065819     [REACT:R-HSA-2426168, REACT:R-HSA-5423646, KEG...

[8529 rows x 1 columns]
8529

In [122]:
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
from rdkit import DataStructs
import numpy as np

# Create generator once (faster)
morgan_gen = rdFingerprintGenerator.GetMorganGenerator(
    radius=2,
    fpSize=1024
)

def get_ecfp_embedding(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None

    fp = morgan_gen.GetFingerprint(mol)
    arr = np.zeros((fp.GetNumBits(),), dtype=np.float32)
    DataStructs.ConvertToNumpyArray(fp, arr)
    return arr

In [123]:
from sklearn.preprocessing import MultiLabelBinarizer
# suppose you have something like:
# chem_id | pathway
# C1      | p53
# C1      | MAPK
# C2      | Apoptosis

pths = list(set(paths['PathwayID'].unique()))
mlb_path = MultiLabelBinarizer(classes=pths)
mlb_path.fit([])
print((pths))

['REACT:R-HSA-187024', 'REACT:R-HSA-8875555', 'KEGG:hsa04392', 'REACT:R-HSA-168270', 'REACT:R-HSA-69202', 'KEGG:hsa04922', 'REACT:R-HSA-109582', 'REACT:R-HSA-2206292', 'KEGG:hsa_M00688', 'REACT:R-HSA-382551', 'REACT:R-HSA-167161', 'REACT:R-HSA-5658442', 'KEGG:hsa04915', 'REACT:R-HSA-844615', 'REACT:R-HSA-5693607', 'REACT:R-HSA-170145', 'KEGG:hsa_M00158', 'REACT:R-HSA-1483171', 'REACT:R-HSA-8948216', 'KEGG:hsa_M00397', 'REACT:R-HSA-156580', 'KEGG:hsa05150', 'REACT:R-HSA-375281', 'KEGG:hsa_M00160', 'REACT:R-HSA-1442490', 'REACT:R-HSA-111933', 'REACT:R-HSA-190861', 'REACT:R-HSA-2142691', 'REACT:R-HSA-3359471', 'REACT:R-HSA-1222449', 'REACT:R-HSA-69563', 'REACT:R-HSA-177162', 'REACT:R-HSA-1474228', 'REACT:R-HSA-5693579', 'REACT:R-HSA-157858', 'REACT:R-HSA-157579', 'REACT:R-HSA-6804116', 'REACT:R-HSA-194315', 'REACT:R-HSA-5602636', 'REACT:R-HSA-6781827', 'KEGG:hsa_M00043', 'REACT:R-HSA-189483', 'REACT:R-HSA-176409', 'REACT:R-HSA-1855215', 'REACT:R-HSA-1299344', 'REACT:R-HSA-77595', 'REACT:R-HSA-5602680', 'REACT:R-HSA-388841', 'KEGG:hsa_M00297', 'REACT:R-HSA-5617472', 'REACT:R-HSA-977347', 'KEGG:hsa04270', 'REACT:R-HSA-112411', 'REACT:R-HSA-83936', 'KEGG:hsa00350', 'REACT:R-HSA-162909', 'REACT:R-HSA-3304347', 'REACT:R-HSA-6811438', 'REACT:R-HSA-68952', 'REACT:R-HSA-156590', 'REACT:R-HSA-446107', 'REACT:R-HSA-6807878', 'KEGG:hsa_M00003', 'KEGG:hsa04120', 'REACT:R-HSA-6804756', 'REACT:R-HSA-6794361', 'REACT:R-HSA-5423646', 'REACT:R-HSA-977225', 'REACT:R-HSA-8847993', 'KEGG:hsa00830', 'REACT:R-HSA-3359478', 'REACT:R-HSA-428790', 'KEGG:hsa_M00141', 'REACT:R-HSA-422085', 'REACT:R-HSA-442745', 'REACT:R-HSA-1855231', 'REACT:R-HSA-170984', 'KEGG:hsa05134', 'KEGG:hsa_M00078', 'REACT:R-HSA-2408552', 'REACT:R-HSA-189200', 'REACT:R-HSA-193697', 'REACT:R-HSA-2046106', 'REACT:R-HSA-2672351', 'REACT:R-HSA-177135', 'REACT:R-HSA-211000', 'REACT:R-HSA-1368108', 'KEGG:hsa04380', 'KEGG:hsa_M00103', 'REACT:R-HSA-5619067', 'KEGG:hsa00561', 'REACT:R-HSA-1368071', 'REACT:R-HSA-168316', 'REACT:R-HSA-168275', 'REACT:R-HSA-5602566', 'REACT:R-HSA-73848', 'KEGG:hsa04919', 'REACT:R-HSA-1236977', 'REACT:R-HSA-5657562', 'REACT:R-HSA-1461973', 'REACT:R-HSA-5689877', 'REACT:R-HSA-112315', 'KEGG:hsa05330', 'REACT:R-HSA-204626', 'REACT:R-HSA-3134973', 'REACT:R-HSA-5693568', 'REACT:R-HSA-3359469', 'REACT:R-HSA-73780', 'REACT:R-HSA-198725', 'REACT:R-HSA-391906', 'REACT:R-HSA-196854', 'KEGG:hsa00250', 'KEGG:hsa_M00104', 'REACT:R-HSA-442755', 'REACT:R-HSA-977441', 'REACT:R-HSA-5083625', 'REACT:R-HSA-8856688', 'REACT:R-HSA-1980143', 'REACT:R-HSA-166665', 'REACT:R-HSA-71288', 'REACT:R-HSA-2980767', 'REACT:R-HSA-2559580', 'REACT:R-HSA-5684264', 'REACT:R-HSA-418889', 'REACT:R-HSA-1980148', 'REACT:R-HSA-975577', 'KEGG:hsa04950', 'REACT:R-HSA-209952', 'KEGG:hsa00380', 'REACT:R-HSA-111463', 'REACT:R-HSA-5358747', 'REACT:R-HSA-5358749', 'REACT:R-HSA-5579006', 'KEGG:hsa04080', 'REACT:R-HSA-389359', 'REACT:R-HSA-5637812', 'REACT:R-HSA-211957', 'KEGG:hsa_M00288', 'REACT:R-HSA-4615885', 'REACT:R-HSA-561048', 'REACT:R-HSA-190374', 'REACT:R-HSA-5099900', 'REACT:R-HSA-3282872', 'REACT:R-HSA-164944', 'REACT:R-HSA-5676594', 'REACT:R-HSA-6804115', 'REACT:R-HSA-5619095', 'REACT:R-HSA-166662', 'REACT:R-HSA-8853338', 'REACT:R-HSA-3249367', 'KEGG:hsa00071', 'REACT:R-HSA-428890', 'KEGG:hsa04216', 'REACT:R-HSA-5602358', 'REACT:R-HSA-354194', 'REACT:R-HSA-1433617', 'REACT:R-HSA-1483115', 'REACT:R-HSA-196849', 'REACT:R-HSA-425410', 'KEGG:hsa05212', 'REACT:R-HSA-8853659', 'REACT:R-HSA-112040', 'REACT:R-HSA-4641265', 'REACT:R-HSA-8849932', 'REACT:R-HSA-5660862', 'REACT:R-HSA-5654700', 'REACT:R-HSA-173599', 'KEGG:hsa_M00682', 'REACT:R-HSA-3928663', 'REACT:R-HSA-198203', 'REACT:R-HSA-2029482', 'REACT:R-HSA-75108', 'REACT:R-HSA-1963640', 'KEGG:hsa04550', 'REACT:R-HSA-167162', 'KEGG:hsa00051', 'REACT:R-HSA-71064', 'REACT:R-HSA-418890', 'REACT:R-HSA-6803204', 'REACT:R-HSA-5656121', 'REACT:R-HSA-429958', 'REACT:R-HSA-210991', 'REACT:R-HSA-1251985', 'REACT:R-HSA-1592389', 'REACT:R-HSA-399721', 'REACT:R-HSA-418886', 'REACT:R-HSA-606279', 'REACT:R-HSA-445717', 'REACT:R-HSA-1257604', 'REACT:R-HSA-112409', 'REACT:R-HSA-1793185', 'KEGG:hsa00400', 'KEGG:hsa04145', 'KEGG:hsa_M00057', 'REACT:R-HSA-69541', 'REACT:R-HSA-112382', 'REACT:R-HSA-168333', 'REACT:R-HSA-400206', 'REACT:R-HSA-674695', 'REACT:R-HSA-179409', 'KEGG:hsa_M00404', 'REACT:R-HSA-449147', 'REACT:R-HSA-193634', 'KEGG:hsa04930', 'REACT:R-HSA-2142696', 'REACT:R-HSA-110314', 'REACT:R-HSA-400451', 'REACT:R-HSA-5696395', 'KEGG:hsa04010', 'REACT:R-HSA-2197563', 'REACT:R-HSA-210744', 'REACT:R-HSA-72649', 'REACT:R-HSA-70895', 'REACT:R-HSA-4720454', 'KEGG:hsa_M00354', 'REACT:R-HSA-8849473', 'REACT:R-HSA-6791055', 'REACT:R-HSA-381676', 'REACT:R-HSA-2428933', 'REACT:R-HSA-4839744', 'REACT:R-HSA-1307965', 'KEGG:hsa_M00035', 'KEGG:hsa05202', 'KEGG:hsa04015', 'REACT:R-HSA-141430', 'REACT:R-HSA-6785470', 'REACT:R-HSA-8866376', 'REACT:R-HSA-1296053', 'REACT:R-HSA-190242', 'REACT:R-HSA-5659729', 'REACT:R-HSA-5602571', 'REACT:R-HSA-5619094', 'REACT:R-HSA-5609977', 'REACT:R-HSA-181430', 'REACT:R-HSA-75109', 'REACT:R-HSA-1855156', 'REACT:R-HSA-211945', 'REACT:R-HSA-156902', 'REACT:R-HSA-1502540', 'REACT:R-HSA-1855184', 'KEGG:hsa_M00403', 'REACT:R-HSA-2993913', 'REACT:R-HSA-5660668', 'REACT:R-HSA-182971', 'KEGG:hsa_M00383', 'KEGG:hsa04940', 'REACT:R-HSA-5654699', 'REACT:R-HSA-187037', 'REACT:R-HSA-392451', 'REACT:R-HSA-381033', 'KEGG:hsa00310', 'REACT:R-HSA-5684996', 'REACT:R-HSA-5693571', 'REACT:R-HSA-3232118', 'REACT:R-HSA-1483191', 'KEGG:hsa_M00100', 'REACT:R-HSA-2871837', 'KEGG:hsa04630', 'REACT:R-HSA-2029485', 'KEGG:hsa04960', 'REACT:R-HSA-6811440', 'REACT:R-HSA-8854214', 'REACT:R-HSA-162699', 'REACT:R-HSA-209968', 'REACT:R-HSA-2173782', 'REACT:R-HSA-2562578', 'REACT:R-HSA-156842', 'KEGG:hsa04137', 'KEGG:hsa_M00151', 'KEGG:hsa_M00684', 'REACT:R-HSA-1296041', 'REACT:R-HSA-5655799', 'REACT:R-HSA-5357801', 'REACT:R-HSA-6807062', 'REACT:R-HSA-2022377', 'REACT:R-HSA-1227986', 'REACT:R-HSA-162587', 'REACT:R-HSA-5250924', 'REACT:R-HSA-399955', 'REACT:R-HSA-5668914', 'REACT:R-HSA-3000171', 'REACT:R-HSA-425366', 'REACT:R-HSA-964827', 'KEGG:hsa00750', 'REACT:R-HSA-5620920', 'REACT:R-HSA-3560782', 'REACT:R-HSA-69656', 'REACT:R-HSA-5679090', 'REACT:R-HSA-167827', 'REACT:R-HSA-400511', 'REACT:R-HSA-111453', 'REACT:R-HSA-5690338', 'REACT:R-HSA-194068', 'REACT:R-HSA-5578997', 'REACT:R-HSA-5579002', 'REACT:R-HSA-70921', 'KEGG:hsa04931', 'REACT:R-HSA-5674135', 'REACT:R-HSA-264642', 'REACT:R-HSA-1280218', 'REACT:R-HSA-5205647', 'REACT:R-HSA-75067', 'REACT:R-HSA-71032', 'REACT:R-HSA-69239', 'KEGG:hsa_M00091', 'REACT:R-HSA-888593', 'REACT:R-HSA-5654704', 'REACT:R-HSA-1295596', 'REACT:R-HSA-6802949', 'REACT:R-HSA-1296346', 'REACT:R-HSA-5649702', 'REACT:R-HSA-975298', 'REACT:R-HSA-2514859', 'REACT:R-HSA-5654727', 'KEGG:hsa_M00072', 'REACT:R-HSA-444257', 'REACT:R-HSA-70221', 'REACT:R-HSA-381753', 'REACT:R-HSA-111931', 'REACT:R-HSA-70171', 'REACT:R-HSA-2465910', 'REACT:R-HSA-76005', 'REACT:R-HSA-977068', 'KEGG:hsa_M00089', 'REACT:R-HSA-196741', 'REACT:R-HSA-5693537', 'KEGG:hsa01100', 'KEGG:hsa_M00410', 'KEGG:hsa00300', 'REACT:R-HSA-5619047', 'REACT:R-HSA-77042', 'REACT:R-HSA-6807505', 'REACT:R-HSA-5619113', 'REACT:R-HSA-418360', 'REACT:R-HSA-194313', 'REACT:R-HSA-198323', 'KEGG:hsa_M00392', 'KEGG:hsa04920', 'REACT:R-HSA-629587', 'REACT:R-HSA-163767', 'REACT:R-HSA-3359463', 'REACT:R-HSA-5387390', 'KEGG:hsa_M00152', 'REACT:R-HSA-4839748', 'REACT:R-HSA-5619044', 'REACT:R-HSA-420597', 'REACT:R-HSA-418990', 'KEGG:hsa_M00005', 'KEGG:hsa00590', 'REACT:R-HSA-1299503', 'REACT:R-HSA-196836', 'REACT:R-HSA-2485179', 'REACT:R-HSA-5579004', 'REACT:R-HSA-2408550', 'REACT:R-HSA-1280215', 'REACT:R-HSA-1912408', 'REACT:R-HSA-1483196', 'REACT:R-HSA-8875791', 'REACT:R-HSA-5250982', 'REACT:R-HSA-174362', 'KEGG:hsa05146', 'REACT:R-HSA-450341', 'REACT:R-HSA-5619039', 'REACT:R-HSA-1300652', 'REACT:R-HSA-2142816', 'REACT:R-HSA-5619045', 'REACT:R-HSA-202403', 'KEGG:hsa04744', 'REACT:R-HSA-73614', 'REACT:R-HSA-8875656', 'KEGG:hsa_M00067', 'KEGG:hsa03460', 'REACT:R-HSA-446388', 'KEGG:hsa04540', 'REACT:R-HSA-442729', 'REACT:R-HSA-3772470', 'REACT:R-HSA-8876725', 'KEGG:hsa01230', 'REACT:R-HSA-5250971', 'REACT:R-HSA-597592', 'REACT:R-HSA-167160', 'REACT:R-HSA-5651801', 'REACT:R-HSA-69017', 'REACT:R-HSA-933541', 'REACT:R-HSA-174417', 'REACT:R-HSA-8854691', 'REACT:R-HSA-167590', 'REACT:R-HSA-434316', 'REACT:R-HSA-112314', 'KEGG:hsa03015', 'REACT:R-HSA-2466712', 'KEGG:hsa03450', 'REACT:R-HSA-390696', 'KEGG:hsa04933', 'REACT:R-HSA-5684045', 'REACT:R-HSA-5619073', 'REACT:R-HSA-5619098', 'KEGG:hsa_M00689', 'KEGG:hsa00230', 'KEGG:hsa_M00133', 'REACT:R-HSA-5663220', 'REACT:R-HSA-6784531', 'REACT:R-HSA-4420332', 'REACT:R-HSA-1169408', 'REACT:R-HSA-5654733', 'KEGG:hsa_M00006', 'REACT:R-HSA-983169', 'REACT:R-HSA-69052', 'REACT:R-HSA-71262', 'REACT:R-HSA-2046104', 'REACT:R-HSA-211916', 'REACT:R-HSA-5693606', 'KEGG:hsa00790', 'REACT:R-HSA-532668', 'REACT:R-HSA-156587', 'KEGG:hsa04913', 'REACT:R-HSA-194138', 'REACT:R-HSA-112043', 'KEGG:hsa05230', 'REACT:R-HSA-416700', 'REACT:R-HSA-456926', 'REACT:R-HSA-194223', 'REACT:R-HSA-997272', 'REACT:R-HSA-159230', 'REACT:R-HSA-111932', 'REACT:R-HSA-975956', 'REACT:R-HSA-5659735', 'REACT:R-HSA-199418', 'REACT:R-HSA-428930', 'REACT:R-HSA-6802957', 'KEGG:hsa03040', 'REACT:R-HSA-187687', 'REACT:R-HSA-389599', 'REACT:R-HSA-111885', 'REACT:R-HSA-3656253', 'REACT:R-HSA-983705', 'REACT:R-HSA-168188', 'REACT:R-HSA-180534', 'REACT:R-HSA-6811555', 'REACT:R-HSA-5685939', 'REACT:R-HSA-5625740', 'REACT:R-HSA-69242', 'REACT:R-HSA-1483148', 'REACT:R-HSA-68881', 'REACT:R-HSA-5654227', 'REACT:R-HSA-381426', 'KEGG:hsa_M00398', 'KEGG:hsa04912', 'KEGG:hsa00520', 'REACT:R-HSA-186797', 'REACT:R-HSA-6803211', 'REACT:R-HSA-164525', 'REACT:R-HSA-212165', 'REACT:R-HSA-611105', 'REACT:R-HSA-1296065', 'REACT:R-HSA-5083627', 'REACT:R-HSA-380612', 'REACT:R-HSA-381042', 'REACT:R-HSA-71240', 'REACT:R-HSA-1296072', 'REACT:R-HSA-381119', 'REACT:R-HSA-5683177', 'REACT:R-HSA-3000157', 'REACT:R-HSA-3359462', 'REACT:R-HSA-8866423', 'REACT:R-HSA-5688031', 'KEGG:hsa04151', 'REACT:R-HSA-157881', 'REACT:R-HSA-111452', 'REACT:R-HSA-5678771', 'REACT:R-HSA-937039', 'KEGG:hsa_M00677', 'REACT:R-HSA-5675221', 'REACT:R-HSA-3371556', 'REACT:R-HSA-75892', 'REACT:R-HSA-389957', 'REACT:R-HSA-3304349', 'REACT:R-HSA-69236', 'REACT:R-HSA-3656534', 'REACT:R-HSA-450520', 'REACT:R-HSA-1483249', 'REACT:R-HSA-195721', 'REACT:R-HSA-192823', 'KEGG:hsa05217', 'REACT:R-HSA-975957', 'REACT:R-HSA-2408499', 'KEGG:hsa05216', 'REACT:R-HSA-5633008', 'REACT:R-HSA-432030', 'REACT:R-HSA-5693532', 'REACT:R-HSA-210747', 'REACT:R-HSA-112126', 'REACT:R-HSA-112310', 'REACT:R-HSA-4411364', 'KEGG:hsa04672', 'REACT:R-HSA-174154', 'REACT:R-HSA-202427', 'REACT:R-HSA-75876', 'REACT:R-HSA-203641', 'KEGG:hsa_M00065', 'KEGG:hsa03008', 'REACT:R-HSA-422356', 'REACT:R-HSA-201451', 'REACT:R-HSA-1489509', 'REACT:R-HSA-1059683', 'REACT:R-HSA-170660', 'REACT:R-HSA-6803529', 'REACT:R-HSA-1483226', 'REACT:R-HSA-4570571', 'REACT:R-HSA-5654712', 'KEGG:hsa_M00554', 'REACT:R-HSA-2033515', 'REACT:R-HSA-2160456', 'REACT:R-HSA-76066', 'REACT:R-HSA-193993', 'REACT:R-HSA-4687000', 'REACT:R-HSA-199220', 'KEGG:hsa04910', 'REACT:R-HSA-168799', 'REACT:R-HSA-480985', 'KEGG:hsa00534', 'REACT:R-HSA-975871', 'REACT:R-HSA-4086398', 'REACT:R-HSA-5619114', 'REACT:R-HSA-5619068', 'REACT:R-HSA-5619056', 'REACT:R-HSA-156584', 'REACT:R-HSA-2206282', 'REACT:R-HSA-444209', 'KEGG:hsa04360', 'REACT:R-HSA-879518', 'KEGG:hsa05161', 'KEGG:hsa04136', 'REACT:R-HSA-2564830', 'KEGG:hsa05200', 'REACT:R-HSA-1855196', 'REACT:R-HSA-168253', 'KEGG:hsa00920', 'REACT:R-HSA-5579000', 'REACT:R-HSA-164378', 'REACT:R-HSA-1834941', 'REACT:R-HSA-73942', 'REACT:R-HSA-389397', 'REACT:R-HSA-433137', 'REACT:R-HSA-421270', 'REACT:R-HSA-4420097', 'REACT:R-HSA-5620916', 'KEGG:hsa04066', 'KEGG:hsa04210', 'REACT:R-HSA-110357', 'REACT:R-HSA-186763', 'REACT:R-HSA-2428928', 'REACT:R-HSA-5652084', 'REACT:R-HSA-427601', 'REACT:R-HSA-176412', 'REACT:R-HSA-428543', 'REACT:R-HSA-418038', 'KEGG:hsa05169', 'REACT:R-HSA-1306955', 'REACT:R-HSA-4641263', 'KEGG:hsa00640', 'KEGG:hsa_M00082', 'REACT:R-HSA-450604', 'REACT:R-HSA-392517', 'REACT:R-HSA-426486', 'REACT:R-HSA-5683678', 'REACT:R-HSA-77285', 'REACT:R-HSA-5576893', 'KEGG:hsa05221', 'REACT:R-HSA-5689603', 'REACT:R-HSA-73893', 'REACT:R-HSA-416482', 'REACT:R-HSA-5654228', 'KEGG:hsa_M00180', 'REACT:R-HSA-3928662', 'REACT:R-HSA-3065678', 'REACT:R-HSA-5628897', 'REACT:R-HSA-5624958', 'KEGG:hsa_M00055', 'REACT:R-HSA-187015', 'REACT:R-HSA-193775', 'REACT:R-HSA-982772', 'REACT:R-HSA-2028269', 'REACT:R-HSA-72203', 'REACT:R-HSA-373760', 'REACT:R-HSA-6787450', 'REACT:R-HSA-1660524', 'REACT:R-HSA-174824', 'REACT:R-HSA-205017', 'REACT:R-HSA-1266695', 'REACT:R-HSA-5693565', 'REACT:R-HSA-174437', 'KEGG:hsa05418', 'REACT:R-HSA-5339716', 'REACT:R-HSA-1839120', 'REACT:R-HSA-6803205', 'REACT:R-HSA-5579031', 'REACT:R-HSA-5334118', 'REACT:R-HSA-549132', 'REACT:R-HSA-5660526', 'REACT:R-HSA-73621', 'REACT:R-HSA-499943', 'REACT:R-HSA-8853336', 'REACT:R-HSA-110331', 'REACT:R-HSA-425986', 'REACT:R-HSA-193681', 'REACT:R-HSA-77286', 'REACT:R-HSA-163560', 'KEGG:hsa04152', 'REACT:R-HSA-69229', 'REACT:R-HSA-205043', 'REACT:R-HSA-389977', 'KEGG:hsa04211', 'KEGG:hsa_M00382', 'REACT:R-HSA-6781823', 'REACT:R-HSA-4641258', 'REACT:R-HSA-70153', 'REACT:R-HSA-69091', 'KEGG:hsa05414', 'KEGG:hsa_M00014', 'REACT:R-HSA-420029', 'KEGG:hsa_M00134', 'REACT:R-HSA-167287', 'REACT:R-HSA-373753', 'KEGG:hsa_M00426', 'REACT:R-HSA-426048', 'REACT:R-HSA-174800', 'REACT:R-HSA-3214841', 'REACT:R-HSA-168336', 'REACT:R-HSA-5638303', 'REACT:R-HSA-190828', 'REACT:R-HSA-2161517', 'REACT:R-HSA-5654689', 'KEGG:hsa04911', 'REACT:R-HSA-6799198', 'KEGG:hsa00120', 'KEGG:hsa_M00070', 'REACT:R-HSA-1221632', 'REACT:R-HSA-975110', 'KEGG:hsa_M00007', 'REACT:R-HSA-195399', 'REACT:R-HSA-1483206', 'REACT:R-HSA-177539', 'REACT:R-HSA-975634', 'REACT:R-HSA-203927', 'REACT:R-HSA-139910', 'REACT:R-HSA-8854521', 'REACT:R-HSA-162658', 'REACT:R-HSA-5579016', 'REACT:R-HSA-418885', 'REACT:R-HSA-211999', 'REACT:R-HSA-182218', 'REACT:R-HSA-181431', 'REACT:R-HSA-3296197', 'REACT:R-HSA-5626978', 'KEGG:hsa02010', 'REACT:R-HSA-162588', 'REACT:R-HSA-975578', 'REACT:R-HSA-432047', 'KEGG:hsa_M00049', 'REACT:R-HSA-2033514', 'REACT:R-HSA-5658471', 'REACT:R-HSA-2122947', 'REACT:R-HSA-73884', 'REACT:R-HSA-1300644', 'REACT:R-HSA-3134975', 'REACT:R-HSA-140342', 'REACT:R-HSA-69231', 'REACT:R-HSA-5603041', 'REACT:R-HSA-73943', 'REACT:R-HSA-2559584', 'REACT:R-HSA-2206296', 'KEGG:hsa00604', 'KEGG:hsa04114', 'KEGG:hsa_M00154', 'KEGG:hsa04150', 'REACT:R-HSA-1482798', 'REACT:R-HSA-73887', 'REACT:R-HSA-3858516', 'REACT:R-HSA-430116', 'REACT:R-HSA-383280', 'REACT:R-HSA-114604', 'REACT:R-HSA-162599', 'REACT:R-HSA-8850843', 'REACT:R-HSA-175474', 'REACT:R-HSA-6798695', 'REACT:R-HSA-1483248', 'REACT:R-HSA-3238698', 'REACT:R-HSA-69478', 'REACT:R-HSA-2206308', 'REACT:R-HSA-156711', 'REACT:R-HSA-5467348', 'REACT:R-HSA-199992', 'REACT:R-HSA-68911', 'REACT:R-HSA-3108214', 'REACT:R-HSA-5682294', 'REACT:R-HSA-1369007', 'REACT:R-HSA-68877', 'REACT:R-HSA-190236', 'KEGG:hsa_M00086', 'REACT:R-HSA-3000178', 'REACT:R-HSA-5693616', 'KEGG:hsa_M00413', 'REACT:R-HSA-8866654', 'KEGG:hsa04330', 'REACT:R-HSA-5683057', 'REACT:R-HSA-983231', 'REACT:R-HSA-174490', 'REACT:R-HSA-8849474', 'KEGG:hsa04725', 'REACT:R-HSA-380972', 'KEGG:hsa05168', 'REACT:R-HSA-69205', 'REACT:R-HSA-1855170', 'REACT:R-HSA-3065679', 'REACT:R-HSA-77108', 'REACT:R-HSA-75896', 'REACT:R-HSA-5358752', 'REACT:R-HSA-3274531', 'REACT:R-HSA-2660826', 'REACT:R-HSA-168249', 'REACT:R-HSA-177128', 'REACT:R-HSA-5619097', 'REACT:R-HSA-109606', 'KEGG:hsa05340', 'REACT:R-HSA-3229121', 'KEGG:hsa_M00396', 'KEGG:hsa00670', 'REACT:R-HSA-3323169', 'REACT:R-HSA-68949', 'REACT:R-HSA-2173793', 'REACT:R-HSA-2022090', 'REACT:R-HSA-451307', 'REACT:R-HSA-2022928', 'KEGG:hsa05160', 'REACT:R-HSA-2691230', 'REACT:R-HSA-397795', 'REACT:R-HSA-74158', 'REACT:R-HSA-399710', 'REACT:R-HSA-5685938', 'REACT:R-HSA-68689', 'REACT:R-HSA-3656243', 'KEGG:hsa_M00387', 'REACT:R-HSA-72306', 'REACT:R-HSA-69273', 'REACT:R-HSA-8866904', 'REACT:R-HSA-997269', 'REACT:R-HSA-8854050', 'REACT:R-HSA-111997', 'REACT:R-HSA-112303', 'KEGG:hsa_M00679', 'REACT:R-HSA-162585', 'REACT:R-HSA-1660508', 'REACT:R-HSA-5368598', 'REACT:R-HSA-442717', 'REACT:R-HSA-168643', 'REACT:R-HSA-880009', 'REACT:R-HSA-5674400', 'KEGG:hsa05224', 'KEGG:hsa_M00380', 'REACT:R-HSA-189451', 'REACT:R-HSA-1614635', 'REACT:R-HSA-2151201', 'REACT:R-HSA-5617833', 'REACT:R-HSA-168303', 'KEGG:hsa04022', 'REACT:R-HSA-5619087', 'REACT:R-HSA-204998', 'REACT:R-HSA-1650814', 'KEGG:hsa_M00690', 'KEGG:hsa_M00034', 'REACT:R-HSA-5610787', 'REACT:R-HSA-8849472', 'REACT:R-HSA-6785807', 'KEGG:hsa05213', 'KEGG:hsa_M00359', 'REACT:R-HSA-73779', 'REACT:R-HSA-72613', 'KEGG:hsa_M00290', 'REACT:R-HSA-163359', 'REACT:R-HSA-69002', 'REACT:R-HSA-447041', 'REACT:R-HSA-200425', 'REACT:R-HSA-196807', 'REACT:R-HSA-168638', 'REACT:R-HSA-3359457', 'REACT:R-HSA-446652', 'REACT:R-HSA-937042', 'REACT:R-HSA-5625970', 'REACT:R-HSA-190377', 'KEGG:hsa00053', 'REACT:R-HSA-448424', 'REACT:R-HSA-69620', 'REACT:R-HSA-1679131', 'REACT:R-HSA-140834', 'REACT:R-HSA-1299287', 'REACT:R-HSA-5601884', 'REACT:R-HSA-1483152', 'REACT:R-HSA-5579012', 'REACT:R-HSA-6791226', 'REACT:R-HSA-5689896', 'KEGG:hsa04975', 'KEGG:hsa_M00683', 'REACT:R-HSA-5213460', 'REACT:R-HSA-8866907', 'REACT:R-HSA-8851680', 'REACT:R-HSA-196783', 'KEGG:hsa00910', 'KEGG:hsa04146', 'KEGG:hsa_M00108', 'REACT:R-HSA-1660661', 'REACT:R-HSA-428540', 'REACT:R-HSA-1222352', 'REACT:R-HSA-8876384', 'REACT:R-HSA-69580', 'REACT:R-HSA-3928665', 'REACT:R-HSA-5632681', 'REACT:R-HSA-141424', 'KEGG:hsa00565', 'REACT:R-HSA-8874081', 'REACT:R-HSA-70614', 'REACT:R-HSA-201688', 'REACT:R-HSA-5621481', 'REACT:R-HSA-72737', 'REACT:R-HSA-109704', 'REACT:R-HSA-2033519', 'REACT:R-HSA-1300642', 'REACT:R-HSA-983168', 'REACT:R-HSA-390247', 'REACT:R-HSA-428542', 'REACT:R-HSA-2990846', 'REACT:R-HSA-6791462', 'REACT:R-HSA-5635838', 'KEGG:hsa_M00147', 'KEGG:hsa_M00549', 'REACT:R-HSA-174495', 'REACT:R-HSA-622323', 'REACT:R-HSA-1474165', 'REACT:R-HSA-2161541', 'KEGG:hsa_M00355', 'REACT:R-HSA-5688354', 'REACT:R-HSA-15869', 'REACT:R-HSA-73927', 'REACT:R-HSA-5578998', 'REACT:R-HSA-5637815', 'REACT:R-HSA-140837', 'KEGG:hsa04115', 'KEGG:hsa_M00027', 'REACT:R-HSA-74160', 'REACT:R-HSA-1368082', 'REACT:R-HSA-453276', 'REACT:R-HSA-73894', 'REACT:R-HSA-190371', 'REACT:R-HSA-2454202', 'KEGG:hsa05032', 'REACT:R-HSA-140179', 'REACT:R-HSA-209776', 'REACT:R-HSA-917937', 'REACT:R-HSA-4793950', 'REACT:R-HSA-5263617', 'REACT:R-HSA-68884', 'REACT:R-HSA-5659898', 'REACT:R-HSA-209563', 'REACT:R-HSA-3322077', 'REACT:R-HSA-430039', 'REACT:R-HSA-168276', 'REACT:R-HSA-5609974', 'REACT:R-HSA-180746', 'REACT:R-HSA-69109', 'REACT:R-HSA-4755609', 'REACT:R-HSA-5607763', 'REACT:R-HSA-2468052', 'KEGG:hsa00512', 'KEGG:hsa00740', 'REACT:R-HSA-202670', 'REACT:R-HSA-5607764', 'REACT:R-HSA-8849468', 'REACT:R-HSA-1660514', 'REACT:R-HSA-112307', 'REACT:R-HSA-1483257', 'KEGG:hsa05016', 'KEGG:hsa01210', 'REACT:R-HSA-379726', 'REACT:R-HSA-173107', 'REACT:R-HSA-111458', 'REACT:R-HSA-5173214', 'REACT:R-HSA-3108232', 'REACT:R-HSA-5358351', 'KEGG:hsa_M00029', 'REACT:R-HSA-193704', 'REACT:R-HSA-111996', 'REACT:R-HSA-110328', 'REACT:R-HSA-2408522', 'REACT:R-HSA-77588', 'KEGG:hsa_M00338', 'REACT:R-HSA-202131', 'REACT:R-HSA-77310', 'REACT:R-HSA-5693538', 'REACT:R-HSA-5358606', 'REACT:R-HSA-4086400', 'KEGG:hsa04810', 'REACT:R-HSA-5654736', 'REACT:R-HSA-5362517', 'REACT:R-HSA-5578996', 'REACT:R-HSA-168888', 'REACT:R-HSA-6804759', 'REACT:R-HSA-392170', 'KEGG:hsa_M00050', 'REACT:R-HSA-5419276', 'REACT:R-HSA-2586552', 'KEGG:hsa05412', 'REACT:R-HSA-112316', 'KEGG:hsa_M00068', 'KEGG:hsa_M00402', 'REACT:R-HSA-2219530', 'REACT:R-HSA-5218920', 'REACT:R-HSA-5663213', 'REACT:R-HSA-446219', 'KEGG:hsa05034', 'REACT:R-HSA-3656535', 'KEGG:hsa_M00384', 'REACT:R-HSA-112311', 'REACT:R-HSA-445989', 'REACT:R-HSA-5654732', 'REACT:R-HSA-1253288', 'REACT:R-HSA-164940', 'REACT:R-HSA-71403', 'KEGG:hsa_M00361', 'KEGG:hsa04740', 'R

In [124]:
disease_slim = (
    df_d
    .groupby("DiseaseID")["SlimMappings"]
    .apply(lambda x: sorted(set(
        i for s in x.dropna() for i in s.split("|")
    )))
)
# slims = []
# for i in range(len(disease_slim)):
#     slims.extend(disease_slim.iloc[i])
# print(len(slims))
# print(len(set(slims)))
print(disease_slim)
mlb_slim = MultiLabelBinarizer()
disease_slim_emb = mlb_slim.fit_transform(disease_slim)
print(mlb_slim.classes_)
disease_slim_emb.shape

DiseaseID
100050     [Cardiovascular disease, Congenital abnormalit...
102200     [Cancer, Endocrine system disease, Nervous sys...
102510     [Congenital abnormality, Musculoskeletal disease]
102530                           [Urogenital disease (male)]
105500     [Mental disorder, Metabolic disease, Nervous s...
                                 ...
D066166    [Congenital abnormality, Connective tissue dis...
D066190         [Nervous system disease, Signs and symptoms]
D066229                                    [Mental disorder]
D066253    [Pathology (anatomical condition), Pathology (...
D066263                                [Pathology (process)]
Name: SlimMappings, Length: 13317, dtype: object
['Animal disease' 'Blood disease' 'Cancer' 'Cardiovascular disease' 'Congenital abnormality' 'Connective tissue disease' 'Digestive system disease' 'Drug-related side effect' 'Ear-nose-throat disease' 'Endocrine system disease' 'Environmental origin disorders' 'Eye disease' 'Fetal disease' 'Genetic disease (inborn)' 'Immune system disease' 'Infant-newborn disease' 'Infection' 'Lymphatic disease' 'Mental disorder' 'Metabolic disease' 'Mouth disease' 'Musculoskeletal disease' 'Nervous system disease' 'Nutrition disorder' 'Occupational disease' 'Parasitic disease' 'Pathology (anatomical condition)' 'Pathology (process)' 'Poisoning' 'Pregnancy complication' 'Respiratory tract disease' 'Signs and symptoms' 'Skin disease' 'Substance-related disorder' 'Urogenital disease (female)' 'Urogenital disease (male)' 'Viral disease' 'Wounds and injuries']

(13317, 38)

In [125]:
cpemb = mlb_path.transform(cpaths['PathwayIDs'])
gpemb = mlb_path.transform(gpaths['PathwayIDs'])
dpemb = mlb_path.transform(dpaths['PathwayIDs'])
print(cpemb.shape)

(8529, 2567)

In [126]:
def get_chemical_embedding(chem_id, smiles):
    ecfp = get_ecfp_embedding(smiles)
    try:
        pw = cpemb[cpaths.index.get_loc(chem_id)]
    except:
        pw = np.zeros(2567, dtype=np.float32)
    return np.concatenate([pw, ecfp]).astype(np.float32)

In [127]:
def get_disease_embedding(disease_id):
    try:
        pw = dpemb[dpaths.index.get_loc(disease_id)]
    except:
        pw = np.zeros(2567, dtype=np.float32)
    try:
        slim = disease_slim_emb[disease_slim.index.get_loc(disease_id)]
    except:
        slim = np.zeros(100, dtype=np.float32)
    
    
    return np.concatenate([pw, slim]).astype(np.float32)

In [132]:
def get_gene_embedding(gene_id):
    try:
        x = gene_emb.loc[gene_emb['GeneSymbol'] == gene_id].values.flatten().tolist()[2:70]
        if(len(x)<1):
            raise
    except:
        x = np.zeros(68, dtype=np.float32)
    try:
        pw = gpemb[gpaths.index.get_loc(gene_id)]
    except:
        pw = np.zeros(2567, dtype=np.float32)
    return np.concatenate([pw, x]).astype(np.float32)

In [133]:
from tqdm import tqdm
for disease_id in tqdm(diseases):
    G.nodes[disease_id]['x'] = get_disease_embedding(disease_id)
for gene_id in tqdm(genes):
    G.nodes[gene_id]['x'] = get_gene_embedding(gene_id)
for chem_id in tqdm(chemicals):
    G.nodes[chem_id]['x'] = get_chemical_embedding(chem_id,known.loc[known["meshID"] == chem_id, "smiles"].iloc[0])

100%|██████████| 7239/7239 [00:00<00:00, 97825.43it/s]
100%|██████████| 28151/28151 [00:39<00:00, 716.88it/s]
 22%|██▏       | 3084/13943 [00:04<00:15, 686.63it/s][16:43:13] WARNING: not removing hydrogen atom without neighbors
[16:43:13] WARNING: not removing hydrogen atom without neighbors
[16:43:13] WARNING: not removing hydrogen atom without neighbors
[16:43:13] WARNING: not removing hydrogen atom without neighbors
 28%|██▊       | 3920/13943 [00:05<00:15, 656.57it/s][16:43:14] WARNING: not removing hydrogen atom without neighbors
 29%|██▊       | 3987/13943 [00:06<00:15, 633.37it/s][16:43:14] WARNING: not removing hydrogen atom without neighbors
 31%|███       | 4266/13943 [00:06<00:14, 667.18it/s][16:43:14] WARNING: not removing hydrogen atom without neighbors
 38%|███▊      | 5246/13943 [00:07<00:12, 669.83it/s][16:43:16] WARNING: not removing hydrogen atom without neighbors
[16:43:16] WARNING: not removing hydrogen atom without neighbors
 40%|████      | 5601/13943 [00:08<00:12, 686.53it/s][16:43:16] WARNING: not removing hydrogen atom without neighbors
[16:43:16] WARNING: not removing hydrogen atom without neighbors
 44%|████▍     | 6152/13943 [00:09<00:11, 675.91it/s][16:43:17] WARNING: not removing hydrogen atom without neighbors
[16:43:17] WARNING: not removing hydrogen atom without neighbors
[16:43:17] WARNING: not removing hydrogen atom without neighbors
 59%|█████▉    | 8261/13943 [00:12<00:08, 685.81it/s][16:43:21] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 9219/13943 [00:14<00:06, 694.05it/s][16:43:22] WARNING: not removing hydrogen atom without neighbors
[16:43:22] WARNING: not removing hydrogen atom without neighbors
 67%|██████▋   | 9358/13943 [00:14<00:06, 665.42it/s][16:43:23] WARNING: not removing hydrogen atom without neighbors
 71%|███████   | 9856/13943 [00:15<00:05, 707.66it/s][16:43:23] WARNING: not removing hydrogen atom without neighbors
[16:43:23] WARNING: not removing hydrogen atom without neighbors
 76%|███████▌  | 10567/13943 [00:16<00:04, 711.95it/s][16:43:24] WARNING: not removing hydrogen atom without neighbors
 82%|████████▏ | 11415/13943 [00:17<00:03, 694.08it/s][16:43:26] WARNING: not removing hydrogen atom without neighbors
[16:43:26] WARNING: not removing hydrogen atom without neighbors
 98%|█████████▊| 13639/13943 [00:20<00:00, 715.23it/s][16:43:29] WARNING: not removing hydrogen atom without neighbors
[16:43:29] WARNING: not removing hydrogen atom without neighbors
[16:43:29] WARNING: not removing hydrogen atom without neighbors
[16:43:29] WARNING: not removing hydrogen atom without neighbors
100%|██████████| 13943/13943 [00:21<00:00, 651.04it/s]

In [134]:
import pickle
with open("bio_graph_raw.pkl", "wb") as f:
    pickle.dump(G, f)

In [136]:
import numpy as np

np.set_printoptions(linewidth=10**9)

with open("graphnodes.txt", "w") as f:
    for g in G.nodes(data=True):
        f.write(str(g) + "\n")